import fs from 'node:fs/promises';

const OUT_DIR=process.env.OUT_DIR||'/tmp/gold-pilot-out';
const PREV_ANALYTICS=process.env.PREV_ANALYTICS||'/tmp/gold-pilot-prev-analytics.json';
const PREV_TIMELINE=process.env.PREV_TIMELINE||'/tmp/gold-pilot-prev-timeline.json';
const UA='Mozilla/5.0 (GoldPilotCloud/1.2; +https://github.com/komininstal-sketch/gold-pilot-cloud)';
const now=Date.now(),iso=new Date(now).toISOString(),OZ=31.1034768;

function clamp(x,a=0,b=100){return Math.max(a,Math.min(b,x));}
function n(v){if(v===null||v===undefined||v==='')return null;if(typeof v==='number')return Number.isFinite(v)?v:null;let s=String(v).trim().replace(/\u00a0/g,' ').replace(/[’']/g,'').replace(/\s+/g,'');if(!s)return null;const ci=s.lastIndexOf(','),di=s.lastIndexOf('.');if(ci>=0&&di>=0)s=di>ci?s.replace(/,/g,''):s.replace(/\./g,'').replace(',','.');else if(ci>=0)s=(s.length-ci-1<=4)?s.replace(',','.'):s.replace(/,/g,'');const x=Number(s.replace(/[^0-9eE+\-.]/g,''));return Number.isFinite(x)?x:null;}
function strip(s=''){return String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim();}
function hash(s=''){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(36);}
async function readJson(path,fallback=null){try{return JSON.parse(await fs.readFile(path,'utf8'));}catch{return fallback;}}
async function fetchText(url,timeout=12000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':UA,'accept-language':'en-US,en;q=0.9,pl;q=0.8'},signal:c.signal,redirect:'follow'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.text();}finally{clearTimeout(t);}}
async function fetchJson(url,timeout=12000){return JSON.parse(await fetchText(url,timeout));}
async function reader(url){try{return await fetchText('https://r.jina.ai/'+url,15000);}catch{return await fetchText(url,12000);}}

const analytics=await readJson(`${OUT_DIR}/analytics-latest.json`,{schema:2,modules:{},snapshot:{}});
const latest=await readJson(`${OUT_DIR}/latest.json`,{});
const prev=await readJson(PREV_ANALYTICS,{snapshot:null});
const prevTimeline=await readJson(PREV_TIMELINE,{events:[]});
const market=latest?.point?.market||{};
const dealers=latest?.point?.dealers||{};

function xmlTag(block,tag){const m=String(block).match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?strip(m[1].replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1')):'';}
function parseFeed(xml,source,domain,url){let blocks=[...String(xml).matchAll(/<item\b[\s\S]*?<\/item>/gi)].map(x=>x[0]);if(!blocks.length)blocks=[...String(xml).matchAll(/<entry\b[\s\S]*?<\/entry>/gi)].map(x=>x[0]);return blocks.slice(0,10).map(b=>{let link=xmlTag(b,'link');if(!link){const m=b.match(/<link[^>]+href=["']([^"']+)["']/i);if(m)link=m[1];}const pub=xmlTag(b,'pubDate')||xmlTag(b,'updated')||xmlTag(b,'published');const d=pub?new Date(pub):new Date();return {title:xmlTag(b,'title'),url:link||url,domain,sourceName:source,tier:'OFFICIAL',ts:isNaN(d)?now:d.getTime()};}).filter(x=>x.title);}
function impact(title){let g=0,u=0,p=0,category='Informacja',mechanism='Brak jednoznacznego wpływu.',confidence=45;const t=String(title||'');if(/rate hike|higher for longer|hawkish|not ready to cut|restrictive policy/i.test(t)){g=-2.4;u=2.7;p=2.2;category='Fed • jastrzębio';confidence=88;mechanism='Wyższe stopy zwykle wspierają USD i ciążą złotu.';}else if(/rate cut|dovish|easing|ready to cut|lower rates|disinflation/i.test(t)){g=2.6;u=-2.6;p=-2;category='Fed • gołębio';confidence=88;mechanism='Łagodniejszy Fed zwykle wspiera złoto i osłabia USD.';}else if(/missile|airstrike|drone strike|invasion|military escalation|attack on|war\b/i.test(t)){g=2.8;u=1.1;p=1.6;category='Eskalacja geopolityczna';confidence=78;mechanism='Risk-off zwykle wspiera złoto, a PLN może słabnąć.';}else if(/ceasefire|truce|peace deal|de-escalat|peace talks/i.test(t)){g=-2.5;u=-.5;p=-.8;category='Deeskalacja';confidence=74;mechanism='Spadek premii za ryzyko może obciążać złoto.';}else if(/tariff|sanction/i.test(t)){g=1.2;u=.4;p=.6;category='Cła / sankcje';confidence=58;mechanism='Wyższa niepewność może wspierać złoto.';}else if(/recession|weak jobs|unemployment rises|economic slowdown|contraction/i.test(t)){g=1.5;u=-1.4;p=-1;category='Słabsze dane USA';confidence=66;mechanism='Słabsze dane mogą zwiększać oczekiwania na łagodniejszy Fed.';}else if(/strong jobs|robust growth|stronger-than-expected|economic expansion/i.test(t)){g=-1.3;u=1.6;p=1.2;category='Mocne dane USA';confidence=68;mechanism='Mocne dane mogą wspierać rentowności i USD.';}return {relevance:Math.max(Math.abs(g),Math.abs(u),Math.abs(p))>.3,category,mechanism,confidence,goldImpact:g,usdImpact:u,usdPlnImpact:p};}
async function gdelt(q,max=20,span='24h'){const u='https://api.gdeltproject.org/api/v2/doc/doc?query='+encodeURIComponent(q)+`&mode=artlist&format=json&maxrecords=${max}&timespan=${span}&sort=datedesc`;try{const j=await fetchJson(u,15000);return (j?.articles||[]).map(a=>({title:a.title||'',url:a.url||'',domain:a.domain||'',sourceName:a.domain||'',tier:'VERIFIED WIRE',ts:Date.now()}));}catch{return [];}}
async function getOfficialAndWire(){const defs=[['Federal Reserve • Monetary Policy','federalreserve.gov','https://www.federalreserve.gov/feeds/press_monetary.xml'],['Federal Reserve • Speeches','federalreserve.gov','https://www.federalreserve.gov/feeds/speeches.xml'],['European Central Bank','ecb.europa.eu','https://www.ecb.europa.eu/rss/press.html']];const rr=await Promise.allSettled(defs.map(d=>fetchText(d[2])));let items=[];rr.forEach((r,i)=>{if(r.status==='fulfilled')items.push(...parseFeed(r.value,...defs[i]));});const wire=await Promise.all([gdelt('domainis:reuters.com gold',20,'24h'),gdelt('domainis:reuters.com "Federal Reserve"',20,'24h'),gdelt('domainis:reuters.com dollar',20,'24h'),gdelt('domainis:apnews.com "Federal Reserve"',15,'24h')]);items.push(...wire.flat());const seen=new Set(),out=[];for(const x of items){const k=hash(x.title.toLowerCase().replace(/[^a-z0-9]+/g,' '));if(seen.has(k))continue;seen.add(k);const im=impact(x.title);if(im.relevance)out.push({...x,...im,key:k});}out.sort((a,b)=>b.ts-a.ts);const top=out.slice(0,18);const avg=k=>top.length?top.slice(0,10).reduce((s,x)=>s+(n(x[k])||0),0)/Math.min(10,top.length):0;return {goldScore:Math.round(clamp(50+avg('goldImpact')*13,10,90)),usdScore:Math.round(clamp(50+avg('usdImpact')*13,10,90)),usdPlnScore:Math.round(clamp(50+avg('usdPlnImpact')*13,10,90)),count:top.length,items:top};}

const RESEARCH=[['WGC','gold','https://www.gold.org/goldhub/research/library',.75],['ING','gold','https://think.ing.com/market/commodities/',1.1],['SAXO','gold','https://www.home.saxo/en-gb/insights/news-and-research/commodities',1.15],['REUTERS','gold','https://www.reuters.com/markets/gold/',1.35],['ING','fx','https://think.ing.com/market/fx/',1.2],['SAXO','fx','https://www.home.saxo/en-gb/insights/news-and-research/forex',1.1],['REUTERS','fx','https://www.reuters.com/markets/currencies/',1.35]];
function signal(t){let g=0,u=0,p=0;const r=[];if(/weaker .*dollar|dollar .*falls|usd .*weak/i.test(t)){g+=1.5;u-=1.7;p-=1.1;r.push('słabszy USD');}if(/stronger .*dollar|dollar .*rises|usd .*strength/i.test(t)){g-=1.5;u+=1.7;p+=1.1;r.push('mocniejszy USD');}if(/rate cut|dovish|lower yields|easing/i.test(t)){g+=1.4;u-=1.3;p-=.8;r.push('łagodniejsze stopy');}if(/rate hike|hawkish|higher yields|higher for longer/i.test(t)){g-=1.4;u+=1.3;p+=.8;r.push('wyższe stopy');}if(/central bank .*gold|official sector buying|etf inflow|investment demand/i.test(t)){g+=1.2;r.push('popyt inwestycyjny');}if(/war|safe[- ]haven|geopolitical|uncertainty/i.test(t)){g+=.6;u+=.3;p+=.3;}return {gold:g,usd:u,usdpln:p,reasons:[...new Set(r)]};}
function candidates(md){const lines=String(md).split(/\r?\n/),out=[];for(const line of lines){const h=/^#{2,5}\s+/.test(line),l=/\[[^\]]{12,220}\]\(https?:\/\/[^)]+\)/.test(line);if(!h&&!l)continue;const title=line.replace(/^#{2,5}\s+/,'').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').trim();if(title.length<15||title.length>220)continue;if(!/(gold|bullion|dollar|usd|currency|fed|rate|yield|inflation|pln|zloty|commodity|market)/i.test(title))continue;out.push(title);if(out.length>=8)break;}return out;}
async function getResearch(){const items=[];for(const [org,focus,url,w] of RESEARCH){try{const md=await reader(url);for(const title of candidates(md).slice(0,2)){const s=signal(title);items.push({org,focus,url,title,...s,weight:w,key:hash(org+'|'+title)});}}catch{}}const fam=[...new Set(items.map(x=>x.org))];let g=0,u=0,p=0,w=0;for(const x of items){g+=x.gold*x.weight;u+=x.usd*x.weight;p+=x.usdpln*x.weight;w+=x.weight;}g=w?g/w:0;u=w?u/w:0;p=w?p/w:0;const pln=g+p*.7;return {items:items.slice(0,16),families:fam,sourceCount:fam.length,goldSignal:g,usdSignal:u,usdPlnSignal:p,plnGoldSignal:pln,score:Math.round(clamp(50+pln*11,18,85)),agreement:Math.round(clamp(35+fam.length*10,30,90)),direction:pln>.45?'WZROSTOWO':pln<-.45?'SPADKOWO':'NEUTRALNIE'};}

function parseFedRanges(text){const t=String(text).replace(/,/g,''),out=[];const rx=/(\d{2,4})\s*[-–]\s*(\d{2,4})\s*(?:bps?|bp)?[^%\n]{0,80}?(\d{1,3}(?:\.\d+)?)\s*%/gi;let m;while((m=rx.exec(t))){let lo=Number(m[1]),hi=Number(m[2]),p=Number(m[3]);if(lo<20&&hi<20){lo*=100;hi*=100;}if(p>=0&&p<=100&&hi>=lo&&hi-lo<=100)out.push({lo,hi,p});}return out.slice(0,8);}
async function getFed(macro){let ranges=[];try{ranges=parseFedRanges(await reader('https://www.cmegroup.com/markets/interest-rates/cme-fedwatch-tool.html'));}catch{}const upper=n(macro?.rows?.DFEDTARU?.value),lower=n(macro?.rows?.DFEDTARL?.value),mid=upper!==null&&lower!==null?(upper+lower)/2*100:null,best=ranges.length?[...ranges].sort((a,b)=>b.p-a.p)[0]:null;let score=n(macro?.scores?.fed2y)||50,detail='CME probabilities nieczytelne • proxy rentowności 2Y';if(best&&mid!==null){const diff=((best.lo+best.hi)/2)-mid;score=clamp(50-diff*.45,20,85);detail=`najbardziej prawdopodobne ${best.lo}-${best.hi} bp • ${best.p.toFixed(1)}%`;}return {score:Math.round(score),detail,ranges,best,currentMid:mid,mode:best?'CME FedWatch':'2Y PROXY'};}

async function stooq(symbol){try{const t=await fetchText(`https://stooq.pl/q/l/?s=${encodeURIComponent(symbol)}&f=sd2t2ohlcv&h&e=csv`);const rows=t.trim().split(/\r?\n/);if(rows.length<2)return null;const h=rows[0].split(',').map(x=>x.toLowerCase()),v=rows[1].split(',');const price=n(v[h.indexOf('close')]);return price>0?{symbol,price,date:v[h.indexOf('date')],time:v[h.indexOf('time')]}:null;}catch{return null;}}
async function getPolandPlus(base){const [fusd,royal,pzu]=await Promise.all([stooq('fusd'),stooq('etcgldrmau.pl'),stooq('etfpzugold.pl')]);return {...base,fusd,royalMint:royal,pzuGold:pzu};}

function integrity(){const spot=n(market.xauUsd),gc=n(market.comexGcUsdOz),live=n(market.plnG),nbp=n(market.nbpGoldPlnG);const d=spot>0&&gc>0?(gc/spot-1)*100:null,nbpD=live>0&&nbp>0?(live/nbp-1)*100:null;let status='OK';if(d!==null&&Math.abs(d)>5)status='BLOCK';else if(d!==null&&Math.abs(d)>2.5)status='WATCH';return {status,comexVsSpotPct:d,nbpVsLivePct:nbpD};}
function dealerMarket(){const tav=dealers?.tavex||null,spot10=n(market.plnG)>0?n(market.plnG)*10:null,sale=n(tav?.salePln),buy=n(tav?.buybackPln);const premium=sale>0&&spot10>0?(sale/spot10-1)*100:null,spread=sale>0&&buy>0?(sale-buy)/sale*100:null;return {spot10,tavexSale:sale,tavexBuyback:buy,premiumPct:premium,spreadPct:spread};}
function entryQuality(dm,evt,cvol,intg){const prem=dm.premiumPct,sp=dm.spreadPct;const premScore=prem===null?50:clamp(82-prem*8,20,85),spreadScore=sp===null?50:clamp(82-sp*6,20,85),eventScore=n(evt?.riskScore)||70,vol=n(cvol?.value),volScore=vol===null?55:vol<=20?72:vol<=25?62:vol<=32?50:38,integrityScore=intg.status==='BLOCK'?10:intg.status==='WATCH'?55:82;return Math.round(premScore*.32+spreadScore*.28+eventScore*.18+volScore*.12+integrityScore*.10);}
function decision(outlook,entry,evt,intg){if(intg.status==='BLOCK')return {title:'NIE PODEJMUJ DECYZJI',detail:'Najpierw potwierdź ceny w źródłach.',outlook,entry};if(evt?.blocking)return {title:'CZEKAJ DO PUBLIKACJI',detail:'Bardzo ważne wydarzenie jest blisko.',outlook,entry};let title='CZEKAJ / OBSERWUJ';if(outlook>=65&&entry>=65)title='ATRAKCYJNE WARUNKI ZAKUPU';else if(outlook>=60&&entry>=48)title='MAŁA TRANSZA / OBSERWUJ';else if(outlook<42)title='CZEKAJ — PERSPEKTYWA SŁABA';else if(entry<40)title='CZEKAJ — CENA WEJŚCIA SŁABA';return {title,detail:`perspektywa ${outlook}/100 • wejście ${entry}/100`,outlook,entry};}

const oldSnap=prev?.snapshot||null;
const politics=await getOfficialAndWire();
const research=await getResearch();
analytics.modules.politics={data:politics,fetchedAt:iso,error:null};
analytics.modules.outlook={data:research,fetchedAt:iso,error:null};
const macro=analytics.modules?.macro?.data||{};
const fed=await getFed(macro);analytics.modules.fed={data:fed,fetchedAt:iso,error:null};
const poland=await getPolandPlus(analytics.modules?.poland?.data||{});analytics.modules.poland={data:poland,fetchedAt:iso,error:null};
const intg=integrity(),dm=dealerMarket(),evt=analytics.modules?.events?.data||{},cvol=analytics.modules?.cvol?.data||{};
const macroScores=macro?.scores||{},flows=analytics.modules?.flows?.data||{},inst=analytics.modules?.institutions?.data||{};
const publicOutlook=Math.round(clamp((macroScores.realYield||50)*.15+(macroScores.dollar||50)*.10+(fed.score||50)*.12+(macroScores.vix||50)*.07+(macroScores.inflation||50)*.06+(macroScores.uncertainty||50)*.03+(politics.goldScore||50)*.14+(research.score||50)*.16+(flows.score||50)*.08+(inst.score||50)*.09,10,90));
const entry=entryQuality(dm,evt,cvol,intg),dec=decision(publicOutlook,entry,evt,intg);
const globalMarkets={spotUsdOz:n(market.xauUsd),comexUsdOz:n(market.comexGcUsdOz),comexBasisPct:n(market.xauUsd)>0&&n(market.comexGcUsdOz)>0?(n(market.comexGcUsdOz)/n(market.xauUsd)-1)*100:null};
analytics.modules.integrity={data:intg,fetchedAt:iso,error:null};analytics.modules.dealerMarket={data:dm,fetchedAt:iso,error:null};analytics.modules.entryQuality={data:{score:entry},fetchedAt:iso,error:null};analytics.modules.decision={data:dec,fetchedAt:iso,error:null};analytics.modules.globalMarkets={data:globalMarkets,fetchedAt:iso,error:null};
analytics.snapshot={...(analytics.snapshot||{}),politics,outlook:research,fed,poland,integrity:intg,dealerMarket:dm,entryQuality:{score:entry},decision:dec,globalMarkets,publicOutlookScore:publicOutlook};analytics.generatedAt=iso;

let timeline=Array.isArray(prevTimeline?.events)?prevTimeline.events:[];const existing=new Set(timeline.map(x=>x.key));function addEvent(x){x.key=x.key||hash([x.kind,x.title,x.url||''].join('|').toLowerCase());if(existing.has(x.key))return;existing.add(x.key);timeline.push(x);}
const oldPol=new Set((oldSnap?.politics?.items||[]).map(x=>hash((x.title||'').toLowerCase())));for(const x of politics.items||[]){const k=hash((x.title||'').toLowerCase());if(!oldPol.has(k))addEvent({kind:'news',title:x.title,detail:`${x.category} • ${x.mechanism}`,importance:Math.abs(x.goldImpact)>=2?3:2,url:x.url||'',ts:x.ts||now,key:'news-'+k});}
const oldRes=new Set((oldSnap?.outlook?.items||[]).map(x=>hash((x.title||'').toLowerCase())));for(const x of research.items||[]){const k=hash((x.title||'').toLowerCase());if(!oldRes.has(k))addEvent({kind:'research',title:`${x.org}: ${x.title}`,detail:(x.reasons||[]).join(', ')||'nowa analiza źródłowa',importance:2,url:x.url||'',ts:now,key:'research-'+k});}
if(oldSnap?.decision?.title&&oldSnap.decision.title!==dec.title)addEvent({kind:'decision',title:`Silnik Decyzyjny: ${oldSnap.decision.title} → ${dec.title}`,detail:dec.detail,importance:3,ts:now});
if(n(oldSnap?.fed?.score)!==null&&Math.abs((fed.score||50)-n(oldSnap.fed.score))>=5)addEvent({kind:'fed',title:`Oczekiwania wobec Fed: ${oldSnap.fed.score} → ${fed.score}/100`,detail:fed.detail,importance:3,ts:now});
if(oldSnap?.integrity?.status&&oldSnap.integrity.status!==intg.status)addEvent({kind:'integrity',title:`Spójność cen: ${oldSnap.integrity.status} → ${intg.status}`,detail:'kontrola Gold API ↔ COMEX',importance:intg.status==='BLOCK'?3:2,ts:now});
if(n(oldSnap?.entryQuality?.score)!==null&&Math.abs(entry-n(oldSnap.entryQuality.score))>=5)addEvent({kind:'entry',title:`Jakość wejścia: ${oldSnap.entryQuality.score} → ${entry}/100`,detail:`premia ${dm.premiumPct?.toFixed?.(2)||'—'}% • spread ${dm.spreadPct?.toFixed?.(2)||'—'}%`,importance:2,ts:now});
timeline=timeline.filter(x=>Number(x.ts)>now-8*24*3600*1000).sort((a,b)=>a.ts-b.ts).slice(-1500);

await fs.writeFile(`${OUT_DIR}/analytics-latest.json`,JSON.stringify(analytics,null,2));
await fs.writeFile(`${OUT_DIR}/timeline.json`,JSON.stringify({schema:1,generatedAt:iso,events:timeline},null,2));
console.log(JSON.stringify({analyticsPlus:true,politics:politics.count,research:research.items.length,fed:fed.mode,decision:dec.title,entry,timeline:timeline.length},null,2));
